### PR TITLE
feat(builder): record dependencies as annotations

### LINKED ISSUE #121: Add used dependencies to package annotations
see https://github.com/adobe/helix-home/issues/94

- during package build, record the npm packages actually used in the final bundle
- add the list of packages as annotation to the action

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #121

creates annotations for dependecies and git location. eg:

```console
$ wsk action get /tripod/helix-services-private/dispatch@3.2.2 | tail +2 | jq -r .annotations
```
```json
[
  {
    "key": "web-export",
    "value": true
  },
  {
    "key": "repository",
    "value": "https://github.com/adobe/helix-dispatch"
  },
  {
    "key": "description",
    "value": "Helix dispatcher service."
  },
  {
    "key": "raw-http",
    "value": false
  },
  {
    "key": "git",
    "value": "https://github.com/adobe/helix-dispatch.git#e7b3a8419ffee312b2b5dd5f6993797675b05cf7"
  },
  {
    "key": "exec",
    "value": "nodejs:10"
  },
  {
    "key": "dependencies",
    "value": [
      {
        "name": "@adobe/helix-epsagon",
        "version": "1.1.13"
      },
      {
        "name": "@adobe/helix-log",
        "transitive": true,
        "version": "4.5.1"
      },
      {
        "name": "@adobe/helix-status",
        "version": "7.1.2"
      },
      {
        "name": "@adobe/openwhisk-action-logger",
        "version": "2.2.0"
      },
      {
        "name": "@adobe/openwhisk-action-utils",
        "version": "4.2.2"
      },
      {
        "name": "axios",
        "transitive": true,
        "version": "0.19.2"
      },
      {
        "name": "balanced-match",
        "transitive": true,
        "version": "1.0.0"
      },
      {
        "name": "big.js",
        "transitive": true,
        "version": "5.2.2"
      },
      {
        "name": "brace-expansion",
        "transitive": true,
        "version": "1.1.11"
      },
      {
        "name": "buffer-from",
        "transitive": true,
        "version": "1.1.1"
      },
      {
        "name": "bunyan",
        "transitive": true,
        "version": "1.8.12"
      },
      {
        "name": "centra",
        "transitive": true,
        "version": "2.4.0"
      },
      {
        "name": "charenc",
        "transitive": true,
        "version": "0.0.2"
      },
      {
        "name": "colorette",
        "transitive": true,
        "version": "1.1.0"
      },
      {
        "name": "concat-map",
        "transitive": true,
        "version": "0.0.1"
      },
      {
        "name": "core-util-is",
        "transitive": true,
        "version": "1.0.2"
      },
      {
        "name": "crypt",
        "transitive": true,
        "version": "0.0.2"
      },
      {
        "name": "debug",
        "transitive": true,
        "version": "3.1.0"
      },
      {
        "name": "dtrace-provider",
        "transitive": true,
        "version": "0.8.8"
      },
      {
        "name": "epsagon",
        "transitive": true,
        "version": "1.51.3"
      },
      {
        "name": "ferrum",
        "version": "1.7.0"
      },
      {
        "name": "follow-redirects",
        "transitive": true,
        "version": "1.5.10"
      },
      {
        "name": "glob",
        "transitive": true,
        "version": "6.0.4"
      },
      {
        "name": "google-protobuf",
        "transitive": true,
        "version": "3.11.4"
      },
      {
        "name": "has-flag",
        "transitive": true,
        "version": "4.0.0"
      },
      {
        "name": "inflight",
        "transitive": true,
        "version": "1.0.6"
      },
      {
        "name": "inherits",
        "transitive": true,
        "version": "2.0.4"
      },
      {
        "name": "is-buffer",
        "transitive": true,
        "version": "1.1.6"
      },
      {
        "name": "isarray",
        "transitive": true,
        "version": "1.0.0"
      },
      {
        "name": "json.sortify",
        "transitive": true,
        "version": "2.2.2"
      },
      {
        "name": "lodash",
        "transitive": true,
        "version": "4.17.15"
      },
      {
        "name": "lodash.isplainobject",
        "transitive": true,
        "version": "4.0.6"
      },
      {
        "name": "md5",
        "transitive": true,
        "version": "2.2.1"
      },
      {
        "name": "minimatch",
        "transitive": true,
        "version": "3.0.4"
      },
      {
        "name": "mkdirp",
        "transitive": true,
        "version": "0.5.1"
      },
      {
        "name": "ms",
        "transitive": true,
        "version": "2.0.0"
      },
      {
        "name": "mv",
        "transitive": true,
        "version": "2.1.1"
      },
      {
        "name": "ncp",
        "transitive": true,
        "version": "2.0.0"
      },
      {
        "name": "once",
        "transitive": true,
        "version": "1.4.0"
      },
      {
        "name": "path-is-absolute",
        "transitive": true,
        "version": "1.0.1"
      },
      {
        "name": "phin",
        "transitive": true,
        "version": "3.4.1"
      },
      {
        "name": "process-nextick-args",
        "transitive": true,
        "version": "2.0.1"
      },
      {
        "name": "psl",
        "transitive": true,
        "version": "1.7.0"
      },
      {
        "name": "readable-stream",
        "transitive": true,
        "version": "2.3.7"
      },
      {
        "name": "request-promise-core",
        "transitive": true,
        "version": "1.1.3"
      },
      {
        "name": "request-promise-native",
        "transitive": true,
        "version": "1.0.8"
      },
      {
        "name": "rimraf",
        "transitive": true,
        "version": "2.4.5"
      },
      {
        "name": "safe-buffer",
        "transitive": true,
        "version": "5.1.2"
      },
      {
        "name": "safe-json-stringify",
        "transitive": true,
        "version": "1.2.0"
      },
      {
        "name": "serverless-http",
        "transitive": true,
        "version": "2.3.2"
      },
      {
        "name": "shimmer",
        "transitive": true,
        "version": "1.2.1"
      },
      {
        "name": "source-map",
        "transitive": true,
        "version": "0.5.7"
      },
      {
        "name": "source-map-support",
        "transitive": true,
        "version": "0.5.16"
      },
      {
        "name": "stealthy-require",
        "transitive": true,
        "version": "1.1.1"
      },
      {
        "name": "string_decoder",
        "transitive": true,
        "version": "1.1.1"
      },
      {
        "name": "supports-color",
        "transitive": true,
        "version": "7.1.0"
      },
      {
        "name": "tough-cookie",
        "transitive": true,
        "version": "2.4.3"
      },
      {
        "name": "triple-beam",
        "transitive": true,
        "version": "1.3.0"
      },
      {
        "name": "util-deprecate",
        "transitive": true,
        "version": "1.0.2"
      },
      {
        "name": "uuid-parse",
        "transitive": true,
        "version": "1.1.0"
      },
      {
        "name": "uuid-to-hex",
        "transitive": true,
        "version": "1.0.3"
      },
      {
        "name": "uuid4",
        "transitive": true,
        "version": "1.1.4"
      },
      {
        "name": "validator",
        "transitive": true,
        "version": "9.4.1"
      },
      {
        "name": "webpack",
        "transitive": true,
        "version": "4.42.1"
      },
      {
        "name": "winston-transport",
        "transitive": true,
        "version": "4.3.0"
      },
      {
        "name": "wrappy",
        "transitive": true,
        "version": "1.0.2"
      },
      {
        "name": "xml-escape",
        "transitive": true,
        "version": "1.1.0"
      }
    ]
  },
  {
    "key": "pkgVersion",
    "value": "3.2.2"
  }
]
```

### CODE REVIEW

**Comment by rofe** [comment]
Does adding the entire dependency tree as annotations noticeably impact performance during activation/execution?

**Comment by tripodsan** [comment]
> Does adding the entire dependency tree as annotations noticeably impact performance during activation/execution?

- it's not the entire dependency tree; only the dependencies that are actually used in the bundle
- It doesn't impact execution, the action gets a bit larger, so I suspect activation might get slower

there would be room to compress the annoation:
- use a comma separated list in the `package@version` format instead of the JSON
- use a simple flag to indicated if a package is transitive (or just ignore this information)

eg:
```
dependencies: "@adobe/helix-epsagon@1.1.13,@adobe/helix-log@4.5.1:t,...",
```

or

```
dependencies: "@adobe/helix-epsagon@1.1.13,...",
dependenciesTrans: "@adobe/helix-log@4.5.1,...",
```

or 
```
dependencies: {
  direct: "@adobe/helix-epsagon@1.1.13,...",
  transitive: "@adobe/helix-log@4.5.1,...",
}
```

**Comment by rofe** [comment]
Thanks for your proposals to further compress the information! I personally like the first version best, and if we don't really need the transitive flag, I'd omit that, too. Or what would we do with it? Wouldn't we have to fix/upgrade a vulnerable package either way?

**Comment by tripodsan** [comment]
> .. and if we don't really need the transitive flag, I'd omit that, too. Or what would we do with it? Wouldn't we have to fix/upgrade a vulnerable package either way?

ok. lets ommit it for now. I thought it might be interresting to se in a potential UI....

**Comment by tripodsan** [comment]
ok, I changed the format to:

```json
  {
    "key": "dependencies",
    "value": "@adobe/helix-epsagon:1.2.0,@adobe/helix-log:4.5.1,@adobe/helix-status:7.1.2,@adobe/openwhisk-action-logger:2.2.0,@adobe/openwhisk-action-utils:4.2.2,axios:0.19.2,balanced-match:1.0.0,big.js:5.2.2,brace-expansion:1.1.11,buffer-from:1.1.1,bunyan:1.8.12,centra:2.4.0,charenc:0.0.2,colorette:1.1.0,concat-map:0.0.1,core-util-is:1.0.2,crypt:0.0.2,debug:3.1.0,dtrace-provider:0.8.8,epsagon:1.58.5,ferrum:1.7.0,follow-redirects:1.5.10,glob:6.0.4,google-protobuf:3.11.4,has-flag:4.0.0,inflight:1.0.6,inherits:2.0.4,is-buffer:1.1.6,isarray:1.0.0,json.sortify:2.2.2,lodash:4.17.15,lodash.isplainobject:4.0.6,md5:2.2.1,minimatch:3.0.4,mkdirp:0.5.1,ms:2.0.0,mv:2.1.1,ncp:2.0.0,once:1.4.0,path-is-absolute:1.0.1,phin:3.4.1,process-nextick-args:2.0.1,psl:1.7.0,readable-stream:2.3.7,request-promise-core:1.1.3,request-promise-native:1.0.8,rimraf:2.4.5,safe-buffer:5.1.2,safe-json-stringify:1.2.0,serverless-http:2.3.2,shimmer:1.2.1,source-map:0.5.7,source-map-support:0.5.16,stealthy-require:1.1.1,string_decoder:1.1.1,supports-color:7.1.0,tough-cookie:2.4.3,triple-beam:1.3.0,util-deprecate:1.0.2,uuid-parse:1.1.0,uuid-to-hex:1.0.3,uuid4:1.1.4,validator:9.4.1,webpack:4.42.1,winston-transport:4.3.0,wrappy:1.0.2,xml-escape:1.1.0"
  },
```

**Comment by trieloff** [comment]
Nice!

**Pull request merged**
